// moveit_collision_guard_node.cpp
// ---------------------------------
// Self-collision guard using MoveIt2's actual collision pipeline
// (moveit_core/collision_detection_fcl) instead of placo/FCL directly:
// an AllowedCollisionMatrix built from the robot's SRDF prunes which link
// pairs are even considered, and collision_detection::CollisionEnvFCL runs
// FCL's broadphase + narrow-phase contact test on what's left - see
// moveit2/moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
// and collision_common.cpp for the reference implementation this mirrors.
//
// The SRDF (daksha_description_full_body/srdf/daksha.srdf) is generated by
// moveit_collision_management/scripts/gen_moveit_srdf.py, which excludes
// parent-child link pairs and pairs that always/never collide across
// sampled configurations - the same exclusion logic
// kinematics/scripts/gen_collision_pairs.py uses for the placo-based
// collision_management package, just emitted as SRDF <disable_collisions>
// entries instead of a JSON allowlist.
//
// Publishes name + position only (position[i] = 1.0 if that joint's child
// link is currently in self-collision, else 0.0) - there is no protective-
// vs-reactive distinction here, just MoveIt's own geometric contact result.
// When collision is true, the exact contacting link pairs are logged (see
// jointStatesCb) so the cause is visible without a separate diagnostic pass.

#include <algorithm>
#include <map>
#include <memory>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>

#include <ament_index_cpp/get_package_share_directory.hpp>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/joint_state.hpp>
#include <srdfdom/model.h>
#include <urdf/model.h>

#include <moveit/collision_detection/collision_common.h>
#include <moveit/collision_detection_fcl/collision_env_fcl.h>
#include <moveit/robot_model/robot_model.h>
#include <moveit/robot_state/robot_state.h>

#include <collision_management/srv/get_collision_status.hpp>

namespace
{
using GetCollisionStatus = collision_management::srv::GetCollisionStatus;

// Fixed output order: right arm, right gripper, left arm, left gripper -
// matches collision_management/collision_guard_node.py's JOINT_ORDER.
std::vector<std::string> buildJointOrder()
{
  std::vector<std::string> order;
  for (int i = 1; i <= 7; ++i)
  {
    order.push_back("right_joint_" + std::to_string(i));
  }
  order.push_back("right_gripper_left_joint");
  order.push_back("right_gripper_right_joint");
  for (int i = 1; i <= 7; ++i)
  {
    order.push_back("left_joint_" + std::to_string(i));
  }
  order.push_back("left_gripper_left_joint");
  order.push_back("left_gripper_right_joint");
  return order;
}

const std::vector<std::string> kJointOrder = buildJointOrder();
}  // namespace

class MoveitCollisionGuardNode : public rclcpp::Node
{
public:
  MoveitCollisionGuardNode() : Node("moveit_collision_guard_node")
  {
    joint_states_topic_ = declare_parameter("joint_states_topic", std::string("/joint_states"));
    collision_topic_ = declare_parameter("collision_topic", std::string("/joint_collision_moveit"));
    service_name_ = declare_parameter("collision_status_service", std::string("get_collision_status_moveit"));
    padding_ = declare_parameter("collision_padding", 0.0);

    const std::string desc_share = ament_index_cpp::get_package_share_directory("daksha_description_full_body");
    urdf_path_ = declare_parameter("collision_urdf_file", desc_share + "/urdf/robot_collision.urdf");
    srdf_path_ = declare_parameter("collision_srdf_file", desc_share + "/srdf/daksha.srdf");

    auto urdf_model = std::make_shared<urdf::Model>();
    if (!urdf_model->initFile(urdf_path_))
    {
      throw std::runtime_error("moveit_collision_guard_node: failed to parse URDF at " + urdf_path_);
    }
    auto srdf_model = std::make_shared<srdf::Model>();
    if (!srdf_model->initFile(*urdf_model, srdf_path_))
    {
      throw std::runtime_error(
          "moveit_collision_guard_node: failed to parse SRDF at " + srdf_path_ +
          " - generate it with moveit_collision_management/scripts/gen_moveit_srdf.py");
    }

    robot_model_ = std::make_shared<moveit::core::RobotModel>(urdf_model, srdf_model);
    collision_env_ = std::make_shared<collision_detection::CollisionEnvFCL>(robot_model_, padding_);
    // checkSelfCollision(req, res, state) with NO AllowedCollisionMatrix ignores the
    // SRDF entirely and checks every link pair, including parent/child pairs that
    // overlap at their shared joint by construction - so an explicit ACM built from
    // the SRDF is required, same as planning_scene::PlanningScene builds internally.
    acm_ = std::make_shared<collision_detection::AllowedCollisionMatrix>(*srdf_model);
    robot_state_ = std::make_shared<moveit::core::RobotState>(robot_model_);
    robot_state_->setToDefaultValues();
    robot_state_->update();

    for (const moveit::core::JointModel* joint_model : robot_model_->getJointModels())
    {
      if (joint_model->getType() == moveit::core::JointModel::REVOLUTE ||
          joint_model->getType() == moveit::core::JointModel::PRISMATIC)
      {
        joint_child_link_[joint_model->getName()] = joint_model->getChildLinkModel()->getName();
      }
    }

    last_status_.name = kJointOrder;
    last_status_.position.assign(kJointOrder.size(), 0.0);

    pub_ = create_publisher<sensor_msgs::msg::JointState>(collision_topic_, 10);
    sub_ = create_subscription<sensor_msgs::msg::JointState>(
        joint_states_topic_, 10,
        std::bind(&MoveitCollisionGuardNode::jointStatesCb, this, std::placeholders::_1));
    service_ = create_service<GetCollisionStatus>(
        service_name_,
        std::bind(&MoveitCollisionGuardNode::statusCb, this, std::placeholders::_1, std::placeholders::_2));

    RCLCPP_INFO(get_logger(),
                "moveit_collision_guard_node up: %s -> %s  (padding=%.4f m)\n"
                "  urdf: %s\n  srdf: %s",
                joint_states_topic_.c_str(), collision_topic_.c_str(), padding_, urdf_path_.c_str(),
                srdf_path_.c_str());
  }

private:
  void jointStatesCb(const sensor_msgs::msg::JointState::SharedPtr msg)
  {
    for (std::size_t i = 0; i < msg->name.size() && i < msg->position.size(); ++i)
    {
      if (robot_model_->hasJointModel(msg->name[i]))
      {
        robot_state_->setVariablePosition(msg->name[i], msg->position[i]);
      }
    }
    robot_state_->update();

    collision_detection::CollisionRequest req;
    req.contacts = true;
    req.max_contacts = 200;
    req.max_contacts_per_pair = 1;
    req.group_name.clear();

    collision_detection::CollisionResult res;
    collision_env_->checkSelfCollision(req, res, *robot_state_, *acm_);

    std::set<std::string> colliding_links;
    for (const auto& entry : res.contacts)
    {
      colliding_links.insert(entry.first.first);
      colliding_links.insert(entry.first.second);
    }

    if (res.collision)
    {
      std::string pairs;
      for (const auto& entry : res.contacts)
      {
        pairs += "  " + entry.first.first + " <-> " + entry.first.second + "\n";
      }
      RCLCPP_INFO_THROTTLE(get_logger(), *get_clock(), 2000, "self-collision, contacts:\n%s", pairs.c_str());
    }

    sensor_msgs::msg::JointState out;
    out.header.stamp = now();
    for (const auto& joint_name : kJointOrder)
    {
      auto it = joint_child_link_.find(joint_name);
      if (it == joint_child_link_.end())
      {
        continue;  // joint not present on this robot model
      }
      const bool in_collision = colliding_links.count(it->second) > 0;
      out.name.push_back(joint_name);
      out.position.push_back(in_collision ? 1.0 : 0.0);
    }

    pub_->publish(out);
    last_status_ = out;
    last_in_collision_ = res.collision;
  }

  void statusCb(const std::shared_ptr<GetCollisionStatus::Request> /*request*/,
                std::shared_ptr<GetCollisionStatus::Response> response)
  {
    response->status = last_status_;
    response->in_collision = last_in_collision_;
  }

  std::string joint_states_topic_;
  std::string collision_topic_;
  std::string service_name_;
  std::string urdf_path_;
  std::string srdf_path_;
  double padding_{ 0.0 };

  moveit::core::RobotModelPtr robot_model_;
  std::shared_ptr<collision_detection::CollisionEnvFCL> collision_env_;
  std::shared_ptr<collision_detection::AllowedCollisionMatrix> acm_;
  moveit::core::RobotStatePtr robot_state_;
  std::map<std::string, std::string> joint_child_link_;

  sensor_msgs::msg::JointState last_status_;
  bool last_in_collision_{ false };

  rclcpp::Publisher<sensor_msgs::msg::JointState>::SharedPtr pub_;
  rclcpp::Subscription<sensor_msgs::msg::JointState>::SharedPtr sub_;
  rclcpp::Service<GetCollisionStatus>::SharedPtr service_;
};

int main(int argc, char** argv)
{
  rclcpp::init(argc, argv);
  int exit_code = 0;
  try
  {
    auto node = std::make_shared<MoveitCollisionGuardNode>();
    rclcpp::spin(node);
  }
  catch (const std::exception& e)
  {
    RCLCPP_FATAL(rclcpp::get_logger("moveit_collision_guard_node"), "startup failed: %s", e.what());
    exit_code = 1;
  }
  rclcpp::shutdown();
  return exit_code;
}
