# =========================================================
# ARM JOINT LIMITS (rad)
# Source: daksha_description_full_body/urdf/robot.urdf <joint><limit>
# =========================================================

left_arm_mit_controller:
  ros__parameters:

    left_joint_1:
      lower: -4.537856
      upper: 0.349066

    left_joint_2:
      lower: -3.141593
      upper: 0.174533

    left_joint_3:
      lower: -1.570796
      upper: 1.570796

    left_joint_4:
      lower: -2.094395
      upper: 0.0

    left_joint_5:
      lower: -3.14159265
      upper: 0.0

    left_joint_6:
      lower: -0.785398
      upper: 0.785398

    left_joint_7:
      lower: -1.570796
      upper: 1.570796

left_gripper_mit_controller:
  ros__parameters:

    left_gripper_left_joint:
      lower: -0.044
      upper: 0.0

right_arm_mit_controller:
  ros__parameters:

    right_joint_1:
      lower: -0.349066
      upper: 4.537856

    right_joint_2:
      lower: -3.141593
      upper: 0.174533

    right_joint_3:
      lower: -1.570796
      upper: 1.570796

    right_joint_4:
      lower: 0.0
      upper: 2.094395

    right_joint_5:
      lower: 0.0
      upper: 3.14159265

    right_joint_6:
      lower: -0.785398
      upper: 0.785398

    right_joint_7:
      lower: -1.570796
      upper: 1.570796

right_gripper_mit_controller:
  ros__parameters:

    right_gripper_right_joint:
      lower: 0.0
      upper: 0.044
